# Project Name
TARGET = daisy_touch_dsp

# Sources
CPP_SOURCES = \
src/main.cpp \
src/ili9341.cpp \
src/touch.cpp \
src/haptic.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and target processor
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
